name: 'SSH Upload'
description: 'Uploads the source directory using SSH protocol on the WWW server'
inputs:
  host:
    description: 'Hostname'
    default: 'localhost'
  ssh-user:
    description: 'SSH username'
    required: true
  ssh-key:
    description: 'SSH private key'
    required: true
  remote-dir:
    description: 'Remote directory where all files will be uploaded'
    default: 'www'
  source-dir:
    description: 'Source directory that will be uploaded'
    default: 'build'
runs:
  using: 'node16'
  main: 'bin/index.js'