name: 'FTP Upload'
description: 'Uploads the source directory using FTP protocol on the WWW server'
inputs:
  host:
    description: 'Hostname'
    default: 'localhost'
  ftp-user:
    description: 'FTP username'
    required: true
  ftp-password:
    description: 'FTP password'
    required: true
  remote-dir:
    description: 'Remote directory where all files will be uploaded'
    default: 'www'
  source-dir:
    description: 'Source directory that will be uploaded'
    default: 'build'
runs:
  using: 'node16'
  main: 'bin/index.js'